### ISSUE TITLE
Add description and webpage

### ISSUE THREAD

**Issue by zuphilip** [citation-style-language/formatter#1]
i.e. http://rintze.zelle.me/style-formatter/

**Comment by rmzelle** [comment]
There already is a link on the style requirements page (last item I
believe).

**Comment by zuphilip** [comment]
I mean in github, i.e. the other direction:

![formatter1](https://cloud.githubusercontent.com/assets/5199995/12703668/dc47061a-c848-11e5-8639-a7ab3a5cdfc3.jpg)

**Comment by rmzelle** [comment]
Done. See https://github.com/citation-style-language/formatter.

(how did you end up at the old http://rintze.zelle.me/style-formatter/ location?)

**Comment by zuphilip** [comment]
Yes, thank you. I googled it, i.e. http://lmgtfy.com/?q=formatter+csl :-)

**Comment by rmzelle** [comment]
I was wondering why it popped up on top. After checking with https://moz.com/researchtools/ose/, my blog post (http://citationstyles.org/2015/07/21/mendeley-and-elsevier-donation-for-2015/) is probably to blame. I'll update that link.

**Comment by zuphilip** [comment]
Two more occurences:

```
https://github.com/citation-style-language/csl-validator/issues/10
https://forums.zotero.org/discussion/39412/problems-with-csl-101-citationstyle-specifications/
```

**Comment by rmzelle** [comment]
You're really helpful :).
