### ISSUE TITLE
Write in smaller case "utf-8"

### ISSUE THREAD

**Issue by zuphilip** [citation-style-language/formatter#2]
The encoding parameter in the XML declaration writes currently `UTF-8` instead of `utf-8` what seems to be more consistent with the other styles in the repo, i.e.

```
<?xml version="1.0" encoding="utf-8"?>
```

Reported in https://github.com/citation-style-language/styles/pull/1874/files#r51348735

**Comment by rmzelle** [comment]
I think the formatter currently doesn't touch that attribute at all, so
lowercase stays lowercase and uppercase stays uppercase. Could force it to
lowercase though.

**Comment by zuphilip** [comment]
I tried it out and it currently changes the lowercase `utf-8` to uppercase `UTF-8`.

**Comment by rmzelle** [comment]
Okay, I'll take a look (might be two weeks or so).

**Comment by rmzelle** [comment]
Hmmm, interesting. When I plug in the style from https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl, Chrome leaves "utf-8" lower-case, while Firefox uppercases it. IE 11 deletes the entire first line (!!).

**Comment by rmzelle** [comment]
Especially with the IE issue, the easiest solution is probably to just do a regexp at the very end (once the XML DOM has been stringified) and manually put in the `<?xml version="1.0" encoding="utf-8"?>` string. Should be an easy fix.

**Comment by rmzelle** [comment]
@zuphilip, can you test this? This works for me on Firefox and Chrome, although I still get strange results on IE11.

(for some reason the alternative regex `<\?xml.+\?>` doesn't catch the initial "<?")

**Comment by rmzelle** [comment]
For some reason things now seem to work correctly. There seem to be some differences in defining regex patterns with literals and as an RegExp object that make my head hurt (see e.g. http://stackoverflow.com/questions/4323456/javascript-regexp-different-results-built-pattern-using-string-using-regexp).

In @fbennett's favorite words:

> Some people, when confronted with a problem, think 
> “I know, I'll use regular expressions.”   Now they have two problems. (http://regex.info/blog/2006-09-15/247)

**Comment by zuphilip** [comment]
Yes, it looks good in my tests. Thank you!
